# Generated by Django 3.2.8 on 2023-01-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='slide_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
